[build]
  publish = "public"
  command = "npm run build"
  environment = { NODE_VERSION = "20" }

# Redirect any URLs with the language code in them already
[[redirects]]
  from = "/sv/*"
  to = "/:splat"
  status = 301
  force = true

# Important: Per shadowing rules, URLs for the
# _non-default_ language-specific content files
# are served without redirects.

# Redirect for end-user’s browser preference override
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 302
  conditions = {Language = ["en"]}

# Default
[[redirects]]
  from = "/*"
  to = "/sv/:splat"
  status = 200

[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "public"

  [plugins.inputs.policies]
    defaultSrc = "'self'"
    fontSrc = "'self' https://cdn.fontshare.com/"
    styleSrc = "'self' https://cdnjs.cloudflare.com/ajax/libs/prism/9000.0.1/themes/ https://api.fontshare.com/v2/"
    objectSrc = "'none'"
    baseUri = "'self'"
    scriptSrc = "'self' https://cpwebassets.codepen.io https://codepen.io https://cdnjs.cloudflare.com/ajax/libs/elasticlunr/0.9.6/"
    frameSrc = "'self' https://youtube.com https://www.youtube.com https://www.youtube-nocookie.com https://cpwebassets.codepen.io https://codepen.io"
    frameAncestors = "'none'"
    imgSrc = "'self' https://i.ytimg.com/"
