[build]
  publish = "public"
  command = "npm run build"
  environment = { NODE_VERSION = "20" }



# Content negotiation for home page
[[redirects]]
  from = "/"
  to = "/en/"
  status = 200
  conditions = {Language = ["en"]}

# Content negotiation for home page
[[redirects]]
  from = "/"
  to = "/sv/"
  status = 200

# Redirect for end-user’s browser preference override
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 302
  conditions = {Language = ["en"]}

# Default
[[redirects]]
  from = "/*"
  to = "/sv/:splat"
  status = 302

# 404 rules
[[redirects]]
  from = "/sv/*"
  to = "/sv/404"
  status = 404

[[redirects]]
  from = "/en/*"
  to = "/en/404"
  status = 404

[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "public"

  [plugins.inputs.policies]
    defaultSrc = "'self'"
    fontSrc = "'self' https://cdn.fontshare.com/"
    styleSrc = "'self' https://cdnjs.cloudflare.com/ajax/libs/prism/9000.0.1/themes/ https://api.fontshare.com/v2/"
    objectSrc = "'none'"
    baseUri = "'self'"
    scriptSrc = "'self' https://cpwebassets.codepen.io https://codepen.io https://cdnjs.cloudflare.com/ajax/libs/elasticlunr/0.9.6/"
    frameSrc = "'self' https://youtube.com https://www.youtube.com https://www.youtube-nocookie.com https://cpwebassets.codepen.io https://codepen.io"
    frameAncestors = "'none'"
    imgSrc = "'self' https://i.ytimg.com/"
