[build]
  publish = "public"
  command = "npm run build"
  environment = { NODE_VERSION = "18" }

[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "public"

  [plugins.inputs.policies]
    defaultSrc = "'self'"
    styleSrc = "'unsafe-hashes'"
    objectSrc = "'none'"
    baseUri = "'self'"
    scriptSrc = "'self' https://www.google-analytics.com https://ssl.google-analytics.com https://www.googletagmanager.com"
    frameSrc = "'self' https://youtube.com https://www.youtube.com https://www.youtube-nocookie.com"
    frameAncestors = "'none'"
    connectSrc = "https://region1.analytics.google.com/"
    imgSrc = "'self' https://region1.analytics.google.com/ https://i.ytimg.com/"
