[build]
  publish = "public"
  command = "npm run build"
  environment = { NODE_VERSION = "20" }

[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "public"

  [plugins.inputs.policies]
    defaultSrc = "'self'"
    styleSrc = "'self' https://cdnjs.cloudflare.com/ajax/libs/prism/9000.0.1/themes/"
    objectSrc = "'none'"
    baseUri = "'self'"
    scriptSrc = "'self' https://cdn.counter.dev/ https://cpwebassets.codepen.io https://codepen.io https://public.codepenassets.com/embed/ https://cdnjs.cloudflare.com/ajax/libs/elasticlunr/"
    frameSrc = "'self' https://youtube.com https://www.youtube.com https://www.youtube-nocookie.com https://cpwebassets.codepen.io https://codepen.io https://public.codepenassets.com/embed/"
    frameAncestors = "'none'"
    imgSrc = "'self' https://i.ytimg.com/"
